apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpkeeptruepvc
  namespace: patricktest
spec:
  volumeName: hpkeeptruepv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "70Mi"
  selector:
    matchLabels:
      namespaceName: patricktest
      storageName: demo-datadir1
