apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpkeepfalsepvc
  namespace: patricktest
spec:
  volumeName: hpkeepfalsepv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "70Mi"
  selector:
    matchLabels:
      namespaceName: patricktest
      storageName: demo-datadir1
