apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    io.enndata.user/alpha-pvhostpathmountpolicy: "none"
    io.enndata.user/alpha-pvhostpathquotaforonepod: "false"
  labels:
    namespaceName: patricktest
    storageName: demo-datadir1
  name: hpnonefalsepv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: "70Mi"
  hostPath:
    path: /k8s_storage/ys/demo-datadir1
  persistentVolumeReclaimPolicy: Retain
